export const data = [
  {
    id: 1,
    title: "Save the Children",
    url: "https://www.savethechildren.net/what-we-do/emergencies/ukraine-crisis",
    img: "stc",
    srcset: "stc@2x.png 2x",
  },
  {
    id: 2,
    title: "Project HOPE",
    url: "https://www.projecthope.org/country/ukraine/",
    img: "hope",
    srcset: "hope@2x.png 2x",
  },
  {
    id: 3,
    title: "UNITED24",
    url: "https://u24.gov.ua/uk",
    img: "u24",
    srcset: "u24@2x.png 2x",
  },
  {
    id: 4,
    title: "International Medical Corps",
    url: "https://internationalmedicalcorps.org/country/ukraine/",
    img: "imc",
    srcset: "imc@2x.png 2x",
  },
  {
    id: 5,
    title: "Medicins Sans Frontieres",
    url: "https://www.msf.org/ukraine",
    img: "msf",
    srcset: "msf@2x.png 2x",
  },
  {
    id: 6,
    title: "RAZOM",
    url: "https://www.razomforukraine.org/",
    img: "razom",
    srcset: "razom@2x.png 2x",
  },
  {
    id: 7,
    title: "Action against hunger",
    url: "https://www.actionagainsthunger.org/location/europe/ukraine/",
    img: "aah",
    srcset: "aah@2x.png 2x",
  },
  {
    id: 8,
    title: "World vision",
    url: "https://www.wvi.org/emergencies/ukraine",
    img: "wv",
    srcset: "wv@2x.png 2x",
  },
  {
    id: 9,
    title: "Serhiy Prytula Charity Foundation",
    url: "https://prytulafoundation.org/en",
    img: "prytula",
    srcset: "prytula@2x.png 2x",
  },
];
